<?php require dirname(__DIR__, 2) . '/api/_bootstrap.php'; $user = currentUser(); $usage = $user ? usageFor($user) : null; ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bum Bum Notes | Leave It to Bum Bum</title><link rel="stylesheet" href="/app.css?v=3"><?php require dirname(__DIR__, 2) . '/includes/analytics.php'; ?><style>
.notes-row{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin-top:8px}
.notes-row .button{margin-top:0}
#notesRec{font-size:20px;padding:16px 30px}
.notes-timer{font-size:34px;font-weight:900}
.notes-status{font-weight:700;margin:14px 0 0}
#notesMeter{width:100%;height:56px;display:block;margin-top:16px;border:2px solid var(--line);border-radius:10px;background:#fff}
#notesText{min-height:170px}
#notesActions button:disabled{opacity:.45;cursor:not-allowed}
select{width:100%;padding:14px;border:2px solid var(--line);border-radius:10px;font:inherit;background:#fff}
</style></head><body><?php $showMeter = true; require dirname(__DIR__, 2) . '/includes/site-header.php'; ?><main class="shell"><p class="eyebrow">Bum Bum's toolbox</p><img class="tool-mascot-page" src="/bum/cat-work.png" alt="Bum Bum in work mode"><h1>Talk it out. We'll write it down.</h1><p class="lede">Hit record and talk it out. Your words appear as you speak, and when you stop your transcript is saved to your private library, ready to copy or download. The audio never leaves your browser. One finished note uses one action.</p>
<?php if (!$user): ?><section class="panel"><h2>Sign in to use Bum Bum Notes</h2><a class="button" href="/account/?next=<?= urlencode('/tools/notes/') ?>">Sign in or create an account</a></section><?php else: ?>
<?php $low = $usage && $usage['remaining'] > 0 && $usage['remaining'] <= (int) ceil($usage['limit'] * 0.2); ?>
<?php $out = ($usage['remaining'] ?? 0) <= 0; ?>
<?php if ($low): ?><div class="nudge">Heads up: only <?= (int) $usage['remaining'] ?> free actions left this month. <a href="/account/#upgrade">Get more actions</a> before they run out.</div><?php endif; ?>
<?php if ($out): ?>
<div id="upgrade-slot"></div>
<?php else: ?>
<section class="panel" id="recorder"><div class="notes-row"><button id="notesRec" class="button" type="button">Record</button><button id="notesStop" class="button secondary" type="button" disabled>Stop</button><span id="notesTimer" class="notes-timer">00:00</span></div><canvas id="notesMeter" width="640" height="56" aria-hidden="true"></canvas><p id="notesStatus" class="notes-status">Ready when you are.</p><label>Transcription language<select id="notesLang"><option value="en-US" selected>English (US)</option><option value="en-GB">English (UK)</option><option value="es-ES">Español</option><option value="fr-FR">Français</option><option value="de-DE">Deutsch</option><option value="it-IT">Italiano</option><option value="pt-BR">Português (BR)</option><option value="zh-CN">中文 (简体)</option><option value="zh-TW">中文 (繁體)</option><option value="yue-Hant-HK">粵語 (香港)</option><option value="ja-JP">日本語</option><option value="ko-KR">한국어</option></select></label><p class="eyebrow" style="margin-top:20px">Transcript <span id="notesSrHint"></span></p><textarea id="notesText" rows="8" readonly placeholder="Your words will appear here while you record..."></textarea><div class="notes-row" id="notesActions"><button id="notesCopy" class="button" type="button" disabled>Copy text</button><button id="notesDlTxt" class="button secondary" type="button" disabled>Download .txt</button><button id="notesDlAudio" class="button secondary" type="button" disabled>Download audio</button><button id="notesSaveEdits" class="button secondary hidden" type="button">Save edits</button><button id="notesAgain" class="button secondary" type="button">Record another</button></div><p id="notesUsage"></p></section>
<section class="panel" id="notesLibrary"><h2 style="margin-top:0">Your notes</h2><div id="notesList"><p class="lede">Loading...</p></div></section>
<div id="upgrade-slot"></div>
<?php endif; ?>
<script>
const TOOL_KEY='notes';
const PERIOD=<?= json_encode($usage['period'] ?? '') ?>;
if(<?= $low ? 'true' : 'false' ?>){const seen='bb_m80_'+PERIOD;if(!localStorage.getItem(seen)){localStorage.setItem(seen,'1');bbTrack('usage_milestone_80',{tool:TOOL_KEY,used:<?= (int) ($usage['used'] ?? 0) ?>,limit:<?= (int) ($usage['limit'] ?? 0) ?>})}}
function upgradeCard(){return `<div class="upgrade-card"><h2>Out of free actions.</h2><p class="lede">You used all <?= (int) ($usage['limit'] ?? 75) ?> free actions this month. Helper gives you 1,500 actions for $12/month. Operator gives you 6,000 actions plus a custom tool built for you in 36 hours for $49/month.</p><p><a class="button" data-plan="helper" href="/checkout/?plan=helper">Get Helper, $12/mo</a> <a class="button secondary" data-plan="operator" href="/checkout/?plan=operator">Get Operator, $49/mo</a></p><p><a href="/account/">See your usage</a></p></div>`}
function bindUpgradeClicks(root,context){root.querySelectorAll('[data-plan]').forEach(a=>a.addEventListener('click',()=>bbTrack('upgrade_clicked',{plan:a.dataset.plan,context:context,tool:TOOL_KEY})))}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
<?php if ($out): ?>
document.querySelector('#upgrade-slot').innerHTML=upgradeCard();
bindUpgradeClicks(document,'page_load');
bbTrack('upgrade_prompt_shown',{tool:TOOL_KEY,context:'page_load'});
<?php else: ?>
const recBtn=document.querySelector('#notesRec');
const stopBtn=document.querySelector('#notesStop');
const timerEl=document.querySelector('#notesTimer');
const statusEl=document.querySelector('#notesStatus');
const srHint=document.querySelector('#notesSrHint');
const langSel=document.querySelector('#notesLang');
const meterCanvas=document.querySelector('#notesMeter');
const textEl=document.querySelector('#notesText');
const usageEl=document.querySelector('#notesUsage');
const copyBtn=document.querySelector('#notesCopy');
const dlTxtBtn=document.querySelector('#notesDlTxt');
const dlAudioBtn=document.querySelector('#notesDlAudio');
const againBtn=document.querySelector('#notesAgain');
const saveEditsBtn=document.querySelector('#notesSaveEdits');
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;
let recording=false,micStream=null,recorder=null,chunks=[],audioCtx=null,analyser=null,meterRAF=0,timerInt=0,startTs=0,recog=null,finalTranscript='',audioBlob=null,audioMime='',attempt=crypto.randomUUID(),savedEntryId=null,savedText='';
if(!SR){srHint.textContent='Live transcription needs Chrome or Edge. Recording and audio download still work fine here.';}
function fmtTime(sec){sec=Math.max(0,Math.floor(sec));return String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0');}
function pickAudioMime(){const c=['audio/webm;codecs=opus','audio/webm','audio/mp4','audio/ogg;codecs=opus'];for(const t of c){if(window.MediaRecorder&&MediaRecorder.isTypeSupported(t))return t;}return '';}
function setStatus(msg,isError){statusEl.textContent=msg;statusEl.classList.toggle('error',!!isError);}
function setActions(on){[copyBtn,dlTxtBtn,dlAudioBtn].forEach(b=>{b.disabled=!on;});}
async function apiCall(payload){const session=await fetch('/api/session.php').then(r=>r.json());const response=await fetch('/api/tools/notes.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,csrf:session.csrf})});let data={};try{data=await response.json()}catch(e){}return{response,data};}
function drawMeter(){const g=meterCanvas.getContext('2d');const W=meterCanvas.width,H=meterCanvas.height;const data=new Uint8Array(analyser.frequencyBinCount);(function frame(){if(!recording)return;meterRAF=requestAnimationFrame(frame);analyser.getByteFrequencyData(data);g.clearRect(0,0,W,H);const bars=48,bw=W/bars;for(let i=0;i<bars;i++){const v=data[Math.floor(i*data.length/bars)]/255;const h=Math.max(3,v*H);g.fillStyle='#ff7448';g.globalAlpha=0.3+v*0.7;g.fillRect(i*bw+bw*0.2,(H-h)/2,bw*0.6,h);}g.globalAlpha=1;})();}
function startRecognition(){if(!SR)return;srHint.textContent='Live: '+langSel.options[langSel.selectedIndex].text;const r=new SR();r.lang=langSel.value;r.continuous=true;r.interimResults=true;r.onresult=e=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const res=e.results[i];const txt=res[0].transcript;if(res.isFinal){finalTranscript+=(finalTranscript&&!/\s$/.test(finalTranscript)?' ':'')+txt.trim()+' ';}else{interim+=txt;}}textEl.value=finalTranscript+interim;textEl.scrollTop=textEl.scrollHeight;};r.onerror=e=>{if(e.error==='not-allowed'||e.error==='service-not-allowed'){srHint.textContent='Transcription was blocked. Check the microphone permission.';}};r.onend=()=>{if(recording){try{r.start();}catch(_){}}};recog=r;try{r.start();}catch(_){}}
function cleanupAudio(){if(micStream){micStream.getTracks().forEach(t=>t.stop());micStream=null;}if(audioCtx){audioCtx.close().catch(()=>{});audioCtx=null;analyser=null;}}
async function startRecording(){if(recording)return;if(!(navigator.mediaDevices&&navigator.mediaDevices.getUserMedia)){setStatus('This browser cannot access the microphone.',true);return;}try{micStream=await navigator.mediaDevices.getUserMedia({audio:true});}catch(e){setStatus('Microphone permission denied.',true);return;}try{audioCtx=new (window.AudioContext||window.webkitAudioContext)();analyser=audioCtx.createAnalyser();analyser.fftSize=256;audioCtx.createMediaStreamSource(micStream).connect(analyser);}catch(e){analyser=null;}chunks=[];const mime=pickAudioMime();try{recorder=new MediaRecorder(micStream,mime?{mimeType:mime}:undefined);}catch(e){cleanupAudio();setStatus('Recording is not supported in this browser.',true);return;}recorder.ondataavailable=e=>{if(e.data&&e.data.size)chunks.push(e.data);};recorder.onstop=onVoiceStop;finalTranscript='';savedEntryId=null;savedText='';saveEditsBtn.classList.add('hidden');attempt=crypto.randomUUID();textEl.value='';textEl.readOnly=true;setActions(false);usageEl.textContent='';startRecognition();try{recorder.start(250);}catch(e){cleanupAudio();if(recog){try{recog.onend=null;recog.stop();}catch(_){}recog=null;}recBtn.disabled=false;setStatus('Recording could not start in this browser.',true);return;}recording=true;startTs=Date.now();if(analyser)drawMeter();timerInt=setInterval(()=>{timerEl.textContent=fmtTime((Date.now()-startTs)/1000);},500);timerEl.textContent='00:00';recBtn.disabled=true;stopBtn.disabled=false;langSel.disabled=true;setStatus(SR?'Recording. Speak now.':'Recording (no live transcription in this browser).');bbTrack('recording_started',{tool:TOOL_KEY});}
function stopRecording(){if(!recording)return;recording=false;clearInterval(timerInt);cancelAnimationFrame(meterRAF);if(recog){try{recog.onend=null;recog.stop();}catch(e){}recog=null;}try{recorder.stop();}catch(e){onVoiceStop();}recBtn.disabled=false;stopBtn.disabled=true;langSel.disabled=false;setStatus('Wrapping up...');}
function onVoiceStop(){audioMime=(recorder&&recorder.mimeType)||'audio/webm';audioBlob=new Blob(chunks,{type:audioMime});cleanupAudio();const text=textEl.value.trim();textEl.readOnly=false;setActions(true);setStatus(text?'Done. Tweak anything I misheard, it saves automatically.':'Hmm, I did not catch any words. Your audio is still available to download.');saveNote(text);}
async function saveNote(text){const key=attempt;attempt=crypto.randomUUID();savedEntryId=null;savedText=text;saveEditsBtn.classList.add('hidden');usageEl.textContent='Saving...';try{const{response,data}=await apiCall({action:'finalize',idempotencyKey:key,transcript:text});if(!response.ok){if(response.status===402){bbTrack('limit_reached',{tool:TOOL_KEY});bbTrack('upgrade_prompt_shown',{tool:TOOL_KEY,context:'limit'});document.querySelector('#upgrade-slot').innerHTML=upgradeCard();bindUpgradeClicks(document.querySelector('#upgrade-slot'),'limit');usageEl.textContent='This note was not counted. Your transcript is safe above.';}else{usageEl.textContent='Could not save this note ('+(data.error||'hmm')+'). Your transcript is safe above.';}return;}bbTrack('action_completed',{tool:TOOL_KEY,used:data.usage.used,limit:data.usage.limit,remaining:data.usage.remaining,chars:text.length});if(data.entry){savedEntryId=data.entry.id;}usageEl.textContent=(data.saved?'Saved to your notes. ':'Nothing to save, that one was all quiet.')+data.usage.remaining+' actions remaining this month.';loadNotes();}catch(e){usageEl.textContent='Could not save this note right now. Your transcript is safe above.';}}
async function loadNotes(){const listEl=document.querySelector('#notesList');if(!listEl)return;const{response,data}=await apiCall({action:'list'});if(!response.ok){listEl.innerHTML='<p class="error">Could not load your notes.</p>';return}const entries=data.entries||[];if(!entries.length){listEl.innerHTML='<p class="lede" style="margin:0">No saved notes yet. Your finished recordings will land here.</p>';return}listEl.innerHTML=entries.map(e=>'<div class="req" data-id="'+e.id+'"><div style="display:flex;justify-content:space-between;gap:12px;align-items:start;flex-wrap:wrap"><div><div style="font-weight:900">'+esc(e.title)+'</div><div style="color:var(--muted);font-size:14px">'+esc(e.created_at)+'</div><div style="margin-top:6px">'+esc(e.preview)+(e.preview.length>=140?'...':'')+'</div></div><div style="white-space:nowrap"><button type="button" class="secondary" data-open style="margin-top:0">Open</button> <button type="button" class="secondary" data-del style="margin-top:0">Delete</button></div></div></div>').join('')}
function stampName(ext){const d=new Date();const p=n=>String(n).padStart(2,'0');return 'bum-bum-note-'+d.getFullYear()+p(d.getMonth()+1)+p(d.getDate())+'-'+p(d.getHours())+p(d.getMinutes())+ext;}
function downloadBlob(blob,filename){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),4000);}
copyBtn.addEventListener('click',async()=>{const t=textEl.value;try{await navigator.clipboard.writeText(t);copyBtn.textContent='Copied!';}catch(e){textEl.select();try{document.execCommand('copy');copyBtn.textContent='Copied!';}catch(_){copyBtn.textContent='Copy failed. Select the text manually.';}}setTimeout(()=>{copyBtn.textContent='Copy text';},1500);});
dlTxtBtn.addEventListener('click',()=>{downloadBlob(new Blob([textEl.value],{type:'text/plain'}),stampName('.txt'));bbTrack('note_downloaded',{tool:TOOL_KEY,format:'txt'});});
dlAudioBtn.addEventListener('click',()=>{if(!audioBlob)return;const m=audioMime.split(';')[0];const ext=m.indexOf('mp4')>=0?'m4a':(m.indexOf('ogg')>=0?'ogg':'webm');downloadBlob(audioBlob,stampName('.'+ext));bbTrack('note_downloaded',{tool:TOOL_KEY,format:'audio'});});
againBtn.addEventListener('click',()=>{textEl.value='';textEl.readOnly=true;finalTranscript='';audioBlob=null;savedEntryId=null;savedText='';saveEditsBtn.classList.add('hidden');setActions(false);usageEl.textContent='';timerEl.textContent='00:00';setStatus('Ready when you are.');recBtn.focus();});
textEl.addEventListener('input',()=>{saveEditsBtn.classList.toggle('hidden',!(savedEntryId&&textEl.value!==savedText));});
saveEditsBtn.addEventListener('click',async()=>{if(!savedEntryId)return;saveEditsBtn.disabled=true;const{response,data}=await apiCall({action:'update',id:savedEntryId,transcript:textEl.value});saveEditsBtn.disabled=false;if(!response.ok){usageEl.textContent=data.error||'Could not save edits.';return}savedText=textEl.value;saveEditsBtn.classList.add('hidden');usageEl.textContent='Edits saved.';loadNotes();});
document.querySelector('#notesList').addEventListener('click',async event=>{const btn=event.target.closest('[data-open],[data-del]');if(!btn)return;const row=event.target.closest('[data-id]');const id=row.dataset.id;if(btn.hasAttribute('data-open')){const{response,data}=await apiCall({action:'get',id});if(!response.ok){alert(data.error||'Could not open that note.');return}textEl.value=data.entry.transcript;textEl.readOnly=false;setActions(true);savedEntryId=data.entry.id;savedText=data.entry.transcript;saveEditsBtn.classList.add('hidden');usageEl.textContent='Opened from your library.';textEl.scrollIntoView({behavior:'smooth',block:'nearest'});}else{if(!confirm('Delete this note? This cannot be undone.'))return;const{response,data}=await apiCall({action:'delete',id});if(!response.ok){alert(data.error||'Could not delete.');return}if(String(savedEntryId)===String(id)){savedEntryId=null;savedText='';saveEditsBtn.classList.add('hidden');}loadNotes();}});
recBtn.addEventListener('click',startRecording);
stopBtn.addEventListener('click',stopRecording);
loadNotes();
<?php endif; ?>
</script><?php endif; ?></main></body></html>
