<?php require dirname(__DIR__, 2) . '/api/_bootstrap.php'; $user = currentUser(); $usage = $user ? usageFor($user) : null; ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Profit Peek | Leave It to Bum Bum</title><link rel="stylesheet" href="/app.css"><?php require dirname(__DIR__, 2) . '/includes/analytics.php'; ?></head><body><header class="shell"><a class="brand" href="/">BB · Leave It to Bum Bum</a><span><?php require dirname(__DIR__, 2) . '/includes/meter.php'; ?> <a href="/account/">Account</a></span></header><main class="shell"><p class="eyebrow">Bum Bum’s toolbox</p><h1>Will this job actually make money?</h1><p class="lede">Add the rough numbers. Profit Peek gives you the expected profit and margin. A successful calculation uses one action.</p>
<?php if (!$user): ?><section class="panel"><h2>Sign in to use Profit Peek</h2><a class="button" href="/account/?next=<?= urlencode('/tools/profit-peek/') ?>">Sign in or create an account</a></section><?php else: ?>
<?php $low = $usage && $usage['remaining'] > 0 && $usage['remaining'] <= (int) ceil($usage['limit'] * 0.2); ?>
<?php if ($low): ?><div class="nudge">Heads up: only <?= (int) $usage['remaining'] ?> free actions left this month. <a href="/account/#upgrade">Get more actions</a> before they run out.</div><?php endif; ?>
<div class="grid"><form id="tool" class="panel"><label>Customer price</label><input name="revenue" type="number" min="0" step="0.01" required><label>Materials</label><input name="materials" type="number" min="0" step="0.01" required><label>Labor</label><input name="labor" type="number" min="0" step="0.01" required><label>Other costs</label><input name="other" type="number" min="0" step="0.01" value="0" required><button>Check this job</button><p id="error" class="error"></p></form><section id="result" class="stat hidden"><span>Estimated profit</span><b id="profit"></b><p><strong id="margin"></strong> margin</p><p id="breakdown"></p><p id="usage"></p></section></div>
<div id="upgrade-slot"></div>
<script>
const TOOL_KEY='profit-peek';
const PERIOD=<?= json_encode($usage['period'] ?? '') ?>;
if(<?= $low ? 'true' : 'false' ?>){const seen='bb_m80_'+PERIOD;if(!localStorage.getItem(seen)){localStorage.setItem(seen,'1');bbTrack('usage_milestone_80',{tool:TOOL_KEY,used:<?= (int) ($usage['used'] ?? 0) ?>,limit:<?= (int) ($usage['limit'] ?? 0) ?>})}}
function upgradeCard(){return `<div class="upgrade-card"><h2>Out of free actions.</h2><p class="lede">You used all <?= (int) ($usage['limit'] ?? 75) ?> free actions this month. Helper gives you 1,500 actions for $12/month. Operator gives you 6,000 actions plus a custom tool built for you in 36 hours for $49/month.</p><p><a class="button" data-plan="helper" href="/checkout/?plan=helper">Get Helper, $12/mo</a> <a class="button secondary" data-plan="operator" href="/checkout/?plan=operator">Get Operator, $49/mo</a></p><p><a href="/account/">See your usage</a></p></div>`}
const form=document.querySelector('#tool');let attempt=crypto.randomUUID();form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('button');button.disabled=true;document.querySelector('#error').textContent='';document.querySelector('#upgrade-slot').innerHTML='';const session=await fetch('/api/session.php').then(r=>r.json());const fields=Object.fromEntries(new FormData(form));const response=await fetch('/api/tools/profit-peek.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...fields,csrf:session.csrf,idempotencyKey:attempt})});const data=await response.json();button.disabled=false;if(!response.ok){if(response.status===402){bbTrack('limit_reached',{tool:TOOL_KEY});bbTrack('upgrade_prompt_shown',{tool:TOOL_KEY,context:'limit'});document.querySelector('#upgrade-slot').innerHTML=upgradeCard();document.querySelectorAll('#upgrade-slot [data-plan]').forEach(a=>a.addEventListener('click',()=>bbTrack('upgrade_clicked',{plan:a.dataset.plan,context:'limit',tool:TOOL_KEY})))}else{document.querySelector('#error').textContent=data.error}return}attempt=crypto.randomUUID();bbTrack('action_completed',{tool:TOOL_KEY,used:data.usage.used,limit:data.usage.limit,remaining:data.usage.remaining});const money=new Intl.NumberFormat(undefined,{style:'currency',currency:'USD'});document.querySelector('#profit').textContent=money.format(data.result.profit);document.querySelector('#margin').textContent=data.result.margin+'%';document.querySelector('#breakdown').textContent=money.format(data.result.revenue)+' revenue minus '+money.format(data.result.cost)+' costs.';document.querySelector('#usage').textContent=data.usage.remaining+' actions remaining this month.';document.querySelector('#result').classList.remove('hidden')});
</script><?php endif; ?></main></body></html>
