<?php require dirname(__DIR__) . '/api/_bootstrap.php'; $user = currentUser(); $usage = $user ? usageFor($user) : null; ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Your account | Leave It to Bum Bum</title><link rel="stylesheet" href="/app.css"></head><body>
<header class="shell"><a class="brand" href="/">BB · Leave It to Bum Bum</a><a href="/#toolbox">Toolbox</a></header><main class="shell">
<?php if (!$user): ?><p class="eyebrow">Your workspace</p><h1>First, tell Bum Bum who you are.</h1><div class="grid"><section class="panel"><h2>Sign in</h2><form data-action="login"><label>Work email</label><input name="email" type="email" required><label>Password</label><input name="password" type="password" minlength="10" required><button>Sign in</button><p class="error"></p></form></section><section class="panel"><h2>Create an account</h2><p>Your free workspace includes 75 completed actions each month.</p><form data-action="register"><label>Work email</label><input name="email" type="email" required><label>Password</label><input name="password" type="password" minlength="10" required><button>Create free account</button><p class="error"></p></form></section></div>
<script>
document.querySelectorAll('form').forEach(form=>form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('button');button.disabled=true;const session=await fetch('/api/session.php').then(r=>r.json());const fields=Object.fromEntries(new FormData(form));const response=await fetch('/api/auth.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...fields,action:form.dataset.action,csrf:session.csrf})});const data=await response.json();if(response.ok){const next=new URLSearchParams(location.search).get('next');location.href=next||'/account/'}else{form.querySelector('.error').textContent=data.error;button.disabled=false}}));
</script>
<?php else: $percent = min(100, (int) round($usage['used'] / max(1, $usage['limit']) * 100)); ?><p class="eyebrow">Your workspace</p><h1><?= ucfirst(htmlspecialchars($user['plan'])) ?> is handling it.</h1><p class="lede"><?= htmlspecialchars($user['email']) ?> · Subscription <?= htmlspecialchars($user['subscription_status']) ?></p><div class="grid"><section class="stat"><span>Actions used</span><b><?= $usage['used'] ?> / <?= $usage['limit'] ?></b><div class="meter"><span style="width:<?= $percent ?>%"></span></div><p><?= $usage['remaining'] ?> actions left in this period.</p></section><section class="panel"><h2>Billing</h2><p>Update your payment method, download invoices, or change your subscription securely through Stripe.</p><button id="billing">Manage billing</button><button id="logout" class="button secondary">Sign out</button><p id="message" class="error"></p></section></div>
<script>
async function session(){return fetch('/api/session.php').then(r=>r.json())}
document.querySelector('#billing').onclick=async()=>{const s=await session();const response=await fetch('/api/portal.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csrf:s.csrf})});const data=await response.json();if(response.ok)location.href=data.url;else document.querySelector('#message').textContent=data.error};
document.querySelector('#logout').onclick=async()=>{const s=await session();await fetch('/api/auth.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout',csrf:s.csrf})});location.reload()};
</script><?php endif; ?></main></body></html>
