<?php require dirname(__DIR__) . '/api/_bootstrap.php'; $user = currentUser(); $usage = $user ? usageFor($user) : null; ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Your account | Leave It to Bum Bum</title><link rel="stylesheet" href="/app.css"><?php require __DIR__ . '/../includes/analytics.php'; ?></head><body>
<header class="shell"><a class="brand" href="/">BB · Leave It to Bum Bum</a><span><?php if ($user) require __DIR__ . '/../includes/meter.php'; ?> <a href="/#toolbox">Toolbox</a></span></header><main class="shell">
<?php if (!$user): ?><p class="eyebrow">Your workspace</p><h1>First, tell Bum Bum who you are.</h1><div class="grid"><section class="panel"><h2>Sign in</h2><form data-action="login"><label>Work email</label><input name="email" type="email" required><label>Password</label><input name="password" type="password" minlength="10" required><button>Sign in</button><p class="error"></p></form></section><section class="panel"><h2>Create an account</h2><p>Your free workspace includes 75 completed actions each month.</p><form data-action="register"><label>Work email</label><input name="email" type="email" required><label>Password</label><input name="password" type="password" minlength="10" required><button>Create free account</button><p class="error"></p></form></section></div>
<script>
document.querySelectorAll('form').forEach(form=>form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('button');button.disabled=true;const session=await fetch('/api/session.php').then(r=>r.json());const fields=Object.fromEntries(new FormData(form));const response=await fetch('/api/auth.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...fields,action:form.dataset.action,csrf:session.csrf})});const data=await response.json();if(response.ok){bbIdentify(fields.email);bbTrack(form.dataset.action==='register'?'signed_up':'signed_in',{});const next=new URLSearchParams(location.search).get('next');location.href=next||'/account/'}else{form.querySelector('.error').textContent=data.error;button.disabled=false}}));
</script>
<?php else: $percent = min(100, (int) round($usage['used'] / max(1, $usage['limit']) * 100));
$isOperator = $user['plan'] === 'operator' && in_array($user['subscription_status'], ['active', 'trialing', 'past_due'], true);
$lowUsage = $usage['remaining'] <= (int) ceil($usage['limit'] * 0.2); ?><p class="eyebrow">Your workspace</p><h1><?= ucfirst(htmlspecialchars($user['plan'])) ?> is handling it.</h1><p class="lede"><?= htmlspecialchars($user['email']) ?> · Subscription <?= htmlspecialchars($user['subscription_status']) ?></p><div class="grid"><section class="stat"><span>Actions used</span><b><?= $usage['used'] ?> / <?= $usage['limit'] ?></b><div class="meter"><span style="width:<?= $percent ?>%"></span></div><p><?= $usage['remaining'] ?> actions left in this period.</p></section><section class="panel"><h2>Billing</h2><p>Update your payment method, download invoices, or change your subscription securely through Stripe.</p><button id="billing">Manage billing</button><button id="logout" class="button secondary">Sign out</button><p id="message" class="error"></p></section></div>
<?php if ($user['plan'] === 'free'): ?>
<section class="panel" id="upgrade"><h2><?= $lowUsage ? 'Almost out of free actions.' : 'Need more than 75 actions a month?' ?></h2><p class="lede"><?= $lowUsage ? 'You are getting real work done. Keep the momentum with more actions every month.' : 'Your free workspace resets every month. Paid plans give you room to grow.' ?></p><div class="plan-cards"><div class="panel"><h2>Helper</h2><p><b>$12</b>/month</p><ul><li>1,500 actions every month</li><li>Every tool in the toolbox</li><li>Cancel anytime</li></ul><a class="button" data-plan="helper" href="/checkout/?plan=helper">Get Helper</a></div><div class="panel"><h2>Operator</h2><p><b>$49</b>/month</p><ul><li>6,000 actions every month</li><li>One custom tool built for you each month</li><li>Delivered in 36 hours or your next month is free</li></ul><a class="button" data-plan="operator" href="/checkout/?plan=operator">Get Operator</a></div></div></section>
<?php elseif ($user['plan'] === 'helper'): ?>
<section class="panel" id="upgrade"><h2>Want a tool built just for you?</h2><p class="lede">Operator adds 6,000 actions a month plus one custom tool request. Describe the annoying task, get a working tool in 36 hours, or your next month is free.</p><a class="button" data-plan="operator" href="/checkout/?plan=operator">Get Operator, $49/mo</a></section>
<?php endif; ?>
<section class="panel" id="requests"><h2>Custom tool requests</h2>
<?php if ($isOperator): ?><p class="lede">One request per month. Delivered within 36 hours or your next month is free.</p><div id="req-list"></div><form id="req-form"><label>Give it a name</label><input name="title" maxlength="180" required placeholder="e.g. Invoice chaser"><label>What annoying task should it handle? What does done look like?</label><textarea name="details" maxlength="5000" required></textarea><button>Send request</button><p id="req-error" class="error"></p></form>
<?php else: ?><p class="lede">Operator includes one custom tool request every month. Describe the annoying task, get a working tool in 36 hours, or your next month is free.</p><a class="button" data-plan="operator" data-context="requests" href="/checkout/?plan=operator">Get Operator, $49/mo</a><?php endif; ?>
</section>
<script>
async function session(){return fetch('/api/session.php').then(r=>r.json())}
document.querySelector('#billing').onclick=async()=>{const s=await session();const response=await fetch('/api/portal.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csrf:s.csrf})});const data=await response.json();if(response.ok)location.href=data.url;else document.querySelector('#message').textContent=data.error};
document.querySelector('#logout').onclick=async()=>{const s=await session();await fetch('/api/auth.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout',csrf:s.csrf})});location.reload()};
document.querySelectorAll('[data-plan]').forEach(a=>a.addEventListener('click',()=>bbTrack('upgrade_clicked',{plan:a.dataset.plan,context:a.dataset.context||'account'})));
<?php if ($isOperator): ?>
function countdown(iso){const ms=new Date(iso).getTime()-Date.now();if(ms<=0)return 'past due';const h=Math.floor(ms/36e5),m=Math.floor(ms%36e5/6e4);return h>0?('in '+h+'h '+m+'m'):('in '+m+'m')}
async function loadRequests(){try{const list=await fetch('/api/requests.php').then(r=>r.json());const box=document.querySelector('#req-list');if(!Array.isArray(list)||!list.length){box.innerHTML='<p class="lede">No requests yet. Your first one is on the house this month.</p>';return}
box.innerHTML=list.map(q=>{const status=q.status==='delivered'?'Delivered':(q.status==='overdue_credited'?'Missed the deadline, free month credited':('In progress, due '+countdown(q.deadline_at)));return `<div class="req"><b>${q.title.replace(/</g,'&lt;')}</b><br><span class="due">${status}</span> · requested ${new Date(q.requested_at).toLocaleDateString()}</div>`}).join('');
const open=list.some(q=>q.status==='open');if(open)document.querySelector('#req-form').innerHTML='<p class="lede">Your request for this month is in progress. Bum Bum is on it.</p>'}catch(e){}}
loadRequests();
const reqForm=document.querySelector('#req-form');if(reqForm)reqForm.addEventListener('submit',async event=>{event.preventDefault();const button=reqForm.querySelector('button');button.disabled=true;document.querySelector('#req-error').textContent='';const s=await session();const fields=Object.fromEntries(new FormData(reqForm));const response=await fetch('/api/requests.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...fields,csrf:s.csrf})});const data=await response.json();if(response.ok){bbTrack('request_submitted',{request_id:data.request.id});location.reload()}else{document.querySelector('#req-error').textContent=data.error;button.disabled=false}});
<?php endif; ?>
</script><?php endif; ?></main></body></html>
